void initBoard(short[], short, short, short, short, short*);
void printBoard(short[], short, short, short, short);
short userInput(short*, short*, short[], short, short, short*, short*, short*, short*, short*);
short calcAdjacent(short, short, short[], short, short, short);
void expandBoard(short, short, short[], short, short, short*);
void cleanup();
void resume();
short getMouseVal(short*);
short clickLogic(short*, short*, short[], short, short, short, short, short*);
void wordArt(short**, short*, short*, short*, short*, short*, short*, short*, short*);
void flushBuffer(short[], short*, short*, short*, short*, short*);
void printSettingsMenu(short, short*, short*, short*, short*);
void sigtstp_handler(int sig);
void sigint_handler(int sig);
