void initBoard(int[], int*, int*, int*);
void printBoard(int[], int, int*, int*);
int userInput(int*, int*, int[], int, int, int*, int*, int*);
int calcAdjacent(int, int, int[], int, int*, int*);
void expandBoard(int, int, int[], int*, int*);
void cleanup(int*);
int getMouseVal(int*);
int clickLogic(int*, int*, int[], int, int*, int*);
void wordArt(int[], int*, int*);
void flushBuffer(int[], int*, int*);
void printSettingsMenu(int, int*, int*, int*);
