void initBoard(int[], int, int, int, int);
void printBoard(int[], int, int, int, int);
int userInput(int*, int*, int[], int, int, int*, int*, int*, int*);
int calcAdjacent(int, int, int[], int, int, int);
void expandBoard(int, int, int[], int, int, int);
void cleanup();
void resume();
int getMouseVal(int*);
int clickLogic(int*, int*, int[], int, int, int, int);
void wordArt(int**, int*, int*, int*, int*, int*);
void flushBuffer(int[], int*, int*, int*, int*, int*);
void printSettingsMenu(int, int*, int*, int*, int*);
void sigtstp_handler(int sig);
void sigint_handler(int sig);
